version: '3'

services:

  app:
    build: .
    command: python chatbot.py
    ports:
      - "5000:5000"
    links:
      - db
  db:
    image: mongo:latest
    hostname: MONGODB_LOCALHOST
    environment:
#      - MONGO_INITDB_DATABASE=MONGODB_DATABASE
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      #- ~/.mongo/data:/data/db
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    ports:
      - 27017:27017


# docker-compose build; docker-compose up -d
# docker exec -it <container-name> bash
# docker logs --tail 50 $service_name
# docker-compose images
# docker-compose logs --tail 20 service_name